########################################################################
##### COPYRIGHT 2018 onwards - Sunit Katkar (sunitkatkar@gmail.com)
########################################################################
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    database: mysql
    show-sql: true 
    generate-ddl: false
    hibernate: 
      ddl-auto: none  

multitenancy: 
  mtapp: 
    dataSources: 
      -
        tenantId: tenant_1 
        url: jdbc:mysql://localhost:13306/dbtenant1?useSSL=false
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver 
      -
        tenantId: tenant_2
        url: jdbc:mysql://localhost:13306/dbtenant2?useSSL=false
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver        